In [1]:
import pandas as pd
data = pd.read_csv("data_small.csv")

In [2]:
data.shape

(454, 3)

In [3]:
data.head()

context  tag  \
0  读者故事：“婆婆陪睡，我成了保姆”   "  茫茫人海中，为防大家走失，请大家   点击上方...    0   
1  剖宫产期间产妇低体温的预测因素    背景与目的   虽然围术期低体温可增加产妇发病率，但少...    1   
2  挨过这波雨雪和降温，温暖和阳光就在前方！还要熬几天？ 这几天出门的小伙伴  抬头望天  都要...    1   
3  杨立新：我不喝豆汁，太馊了！陈佩斯回答7个字让网友坐不住了！ 杨立新：我不喝豆汁，太馊了！陈...    1   
4  上汽大众2018年销量继续领跑国内乘用车市场，背后的实力值得深究  2018年的车市格外严峻...    1   

                                               words  
0  读者 故事 婆婆 陪 睡 我成 保姆 茫茫人海 中 为防 走失 请 点击 上方 婆媳关系 婚...  
1  剖宫产 期间 产妇 低 体温 预测 因素 背景 目的 围术期 低 体温 增加 产妇 发病率 ...  
2  挨过 这波 雨雪 降温 温暖 阳光 前方 熬 几天 几天 出门 小伙伴 抬头 望天 叹一口气...  
3  杨立新 喝 豆汁 太 馊 陈佩斯 回答 字 网友 坐不住 杨立新 喝 豆汁 太 馊 陈佩斯 ...  
4  上汽 大众 2018 年销量 领跑 国内 乘用车 市场 背后 实力 值得 深究 2018 车...

In [4]:
from keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer(num_words=90000) # 单词表中最频繁的90000个单词，也就是列数
tokenizer.fit_on_texts(data['words']) # 要用以训练的文本列表，['i love you', 'you love me too']，Series应该也可以
print(tokenizer.word_index) # 词表序号
print(tokenizer.word_counts) # 词频统计

Using TensorFlow backend.


{'一逃': 25488, '龙头企业': 17044, 'dna': 1907, '饥时': 23809, '送戏': 25960, '汤菜': 25319, '变量': 6028, '闭目养神': 16917, '冲过来': 12242, '海洋工程': 24338, '病床': 9163, '人拉低': 30248, '亮点': 3853, '式样': 2092, '应龙': 19372, '潮涨潮落': 26125, '小伙子': 23505, '太': 135, '培养基': 21075, '孔洞': 4105, '中后期': 31558, '78': 23186, '驾驶证': 10763, '第一分': 32634, '收起': 28842, '养命': 20000, '彻底解决': 31956, '1200': 12624, '所圈': 27323, '藁城': 19410, '途乐': 3880, '搞笑': 33750, '某位': 29458, '光学': 24313, '只卖': 7613, 'by': 15042, '提示': 1330, '金皇帝': 23980, '2013': 2537, '内科': 29940, '脑血管': 5554, '料酒': 20631, '自动': 1843, '早年': 4378, '亡': 8914, '栾城': 19409, '只接': 33342, '席卷': 12192, '遇前': 28888, '占优': 27118, '沙俄': 13330, '英武': 30145, '夺回': 9849, '父母官': 33666, '原平市': 12317, '师生': 3760, '节': 7346, '过多': 2549, '浓香': 18783, '坪地': 654, '附身': 29424, '功德圆满': 13566, '田壮壮': 21984, '五星级': 15482, '蠕动': 31103, '分庄': 30318, '种族': 4098, '大蒜': 33569, '房门': 7841, '刹车': 5418, '尽致': 28204, '事太': 27930, '生肖': 224, '恒立': 26823, '之下': 2386, '已至': 18719, '重在养': 28365

In [5]:
binary_matrix = tokenizer.texts_to_matrix(data['words']) # 实际上这是一个binary的向量，如果dictionary的下标为i的那个词在这个string中出现了，那么就给一个1，否则给0
print(binary_matrix) # numpy.ndarray
count_matrix = tokenizer.texts_to_matrix(data['words'], mode='count') # 每个位置代表词频数
print(count_matrix) # numpy.ndarray
freq_matrix = tokenizer.texts_to_matrix(data['words'], mode='freq') # 每个位置代表频率
print(freq_matrix) # numpy.ndarray
tfidf_matrix = tokenizer.texts_to_matrix(data['words'], mode='tfidf') # 每个位置代表tfidf值
print(tfidf_matrix) # numpy.ndarray

[[0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 3. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 3. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0.         0.00238284 0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.0078329  0.00261097 ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]
[[0.         2.40905771 0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 ...
 [0.         0.     

In [6]:
texts_sequences = tokenizer.texts_to_sequences(data['words']) # 返回各个词序号的列表
print(texts_sequences) # 嵌套的列表

[[3145, 104, 1321, 827, 306, 15954, 5988, 5989, 1, 10270, 10271, 71, 783, 3146, 4927, 508, 783, 7616, 10272, 7617, 2501, 228, 3145, 3147, 104, 3, 5990, 1498, 4159, 10273, 4928, 10274, 3147, 7618, 5991, 15955, 545, 622, 15956, 15957, 416, 4929, 117, 40, 1770, 4160, 597, 4161, 10275, 4162, 15958, 126, 985, 1771, 1411, 15959, 152, 1499, 1500, 2789, 4930, 10276, 1632, 5992, 15960, 744, 5993, 10277, 1500, 1501, 10278, 10279, 15961, 10280, 296, 10275, 15962, 15963, 416, 347, 15964, 283, 297, 4931, 27, 15965, 5994, 4932, 597, 143, 546, 10281, 1322, 10282, 284, 10283, 509, 4, 1412, 416, 284, 4, 660, 1237, 10284, 448, 10285, 546, 434, 45, 87, 1633, 3613, 1634, 448, 138, 2790, 3, 935, 1772, 1918, 76, 5995, 7619, 1773, 597, 705, 986, 37, 2502, 623, 3614, 416, 284, 3615, 4163, 4933, 22, 15966, 1919, 1322, 416, 4, 3616, 41, 434, 3616, 4, 434, 62, 4934, 3148, 547, 597, 1158, 15967, 3617, 25, 491, 10286, 467, 10287, 546, 416, 10288, 597, 79, 2791, 15968, 416, 3618, 15969, 1238, 546, 15970, 95, 58, 49

In [7]:
from keras.preprocessing.sequence import pad_sequences
texts_sequences_padding = pad_sequences(texts_sequences, maxlen=1000, padding='post', truncating='post') # 短的从后面补0，长的从后面截断
print(texts_sequences_padding) # numpy.ndarray

[[ 3145   104  1321 ... 10326   126  2803]
 [ 2808   176  1244 ...     0     0     0]
 [10393 10394 10395 ...     0     0     0]
 ...
 [ 2362   871 33743 ...     0     0     0]
 [ 1320  3181 10265 ...     0     0     0]
 [15953   107  2154 ...     0     0     0]]
